# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Juyoung Park
description: J.Park's Homepage
baseurl: "/bay"
url: "https://lamprolite.github.io"
og_image: /assets/img/profile_picture.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: False
  contact:
    - type: email
      name: Email
      value: lamprolite@pusan.ac.kr 
    - type: call
      name: Call
      value: +82) 510-3248
    - type: pin
      name: Location
      value: 2, Busandaehak-ro 63beon-gil, Geumjeong-gu, Busan, Republic of Korea 46241
    - type: destination
      name: Office
      value: Enter Building and take the stairs to Office 305


      
  follow:
   # - type: twitter
  #  name: Twitter
  #    link: http://twitter.com/YourTwitterUsername
   #   username: "@YourTwitterUsername"
   # - type: facebook
   #   name: Facebook
   #   link: http://facebook.com/YourFacebookUsername
   # - type: linkedin
   #   name: LinkedIn
   #   link: http://linkedin.com/in/YourLinkedInUsername
    - type: github
      name: GitHub
      link: http://github.com/Lamprolite
    - type: youtube
      name: Youtube
      link: https://www.youtube.com/@lamprolite
    - type: blog
      name: Blog
    - link: https://blog.naver.com/lamprolite

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
